username=APIPROCESSING
password=2xx@Success
baseURI=https://springboot-lms-userskill.herokuapp.com
userAPIendpoint=Users
userSkillsMapEndpointForUser=UserSkillsMap
usersSkillsMap=UsersSkillsMap
skillAPI=Skills
userSkillMapAPI=UserSkills